apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  channel-teams-url: https://viewsonic0.webhook.office.com/webhookb2/dec9ecc3-62e8-43ac-97ae-7822b5169951@f7a08210-8cd2-459f-9459-ddb19785f376/IncomingWebhook/3eee8377f75142b69096ffa6cd9b0f69/4ce3d233-58fd-44ae-b8f5-758b92fd1dca/V2GanZfQUzDGOTJywsVQpptSndhb6F_Fx_1kXkSwtRG9M1