apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  service.slack: |
    token: "https://hooks.slack.com/services/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"
