apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  channel-teams-url: "https://viewsonic0.webhook.office.com/webhookb2/dec9ecc3-62e8-43ac-97ae-7822b5169951@f7a08210-8cd2-459f-9459-ddb19785f376/IncomingWebhook/bb10ddf02fff4c73904f87f8523c4077/4ce3d233-58fd-44ae-b8f5-758b92fd1dca/V2JkHm3lklfAhcWOJJQAZZdqd8-v3W0Me3EM4g5w0UUVg1"