name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Simulate build
        run: |
          echo "Simulating successful build"
          exit 0  # Uncomment this to simulate failure

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./argoCDtest
          push: false
          tags: myapp:latest