name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to server
        run: echo "Pretend deploying to server here"
      
      - name: Simulate build
        run: |
          echo "Simulating successful build"
          exit 1  # Uncomment this to simulate failure
