name: Trigger notification

on:
  push:
    branches:
      - feat/notifications

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy deploy
        run: echo "Deploying..."

  notify:
    uses: ./.github/workflows/notify.yml
    needs: deploy
    with:
      status: success
      workflow: Trigger notification
      branch: feat/notifications
      actor: ${{ github.actor }}
      run_id: ${{ github.run_id }}